* Coding challenge
*** *The most important rules in our version:*
- A player wins by completing a row, column, or diagonal.
- There's a free slot (always on) in the middle
- You can have multiple bingos
*** The challenge
*** *Must haves:*
- Build a fully working Bingo App using ReactJS **respecting the 3 basic rules explained above**.
- The game **must** always fit nicely to any screen-size (e.g. mobile).
- **Design your own version** – our game is an example. Be creative and pick your own design!
- Having a bingo requires some **nice visual reward**. You don't need to use confetti – choose something you believe fits best.
- Think of multiple gamers playing the Bingo together.. ensure that winning the game is possible and fair.
- **Add something new.** Come up with something you would enjoy while playing the game.
*** Optional:
- Choose your own topic – if you want. You can stick to Online Conferencing, but if there's another similar situation you can think of – use it.
*** Tools & time
- You should use ReactJS (latest version) – the rest is up to you!
If you want to use whatever CSS / JS Libraries etc. Do it – but explain why.
- The challenge should not take longer than 4 hours. We do not expect to receive a bug-free and polished version – but something working 🤓
