const data = [
  {id: 1, description: "Number go up", active: false},
  {id: 2, description: "Shitcoin", active: false},
  {id: 3, description: "DogeCoin", active: false},
  {id: 4, description: "HODL", active: false},
  {id: 5, description: "Bitcoin", active: false},
  {id: 6, description: "Stack sats", active: false},
  {id: 7, description: "Ethereum is a supercomputer", active: false},
  {id: 8, description: "Blockchain", active: false},
  {id: 9, description: "21 million", active: false},
  {id: 10, description: "Fiatmoney", active: false},
  {id: 11, description: "Satoshi Nakamoto", active: false},
  {id: 12, description: "Proof of Work", active: false},
  {id: 13, description: "Censorship-resistance", active: false},
  {id: 14, description: "Mining", active: false},
  {id: 15, description: "Whitepaper", active: false},
  {id: 16, description: "Public Key", active: false},
  {id: 17, description: "Wallet", active: false},
  {id: 18, description: "CoinJoin", active: false},
  {id: 19, description: "Full Node", active: false},
  {id: 20, description: "HFSP", active: false},
  {id: 21, description: "Decentralization", active: false},
  {id: 22, description: "Crypto Twitter", active: false},
  {id: 23, description: "Monero", active: false},
  {id: 24, description: "Fungibility", active: false},
  {id: 25, description: "Financial crisis", active: false},
  {id: 26, description: "SHA256", active: false},
  {id: 27, description: "Alice/Bob", active: false},
  {id: 28, description: "China", active: false},
  {id: 29, description: "SEC", active: false},
  {id: 30, description: "Elon Musk", active: false},
  {id: 31, description: "Michael Saylor", active: false},
];

module.exports = data;
